# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'PromiseKit', '~> 6.8.4'	
  pod 'SwiftyJSON', '~> 4.0'
  pod 'RealmSwift'

 target 'WeatherAppTests' do
      inherit! :search_paths
  end
end

